import type { Permission } from "@/generated/prisma/enums";

export const ALL_PERMISSIONS: Permission[] = [
  "VIEW_PRODUCTS",
  "ADD_PRODUCTS",
  "EDIT_PRODUCTS",
  "DELETE_PRODUCTS",
  "CHANGE_PRICES",
  "BULK_PRICE_UPDATE",
  "IMPORT_EXPORT",
  "CREATE_BILLS",
  "CANCEL_BILLS",
  "APPLY_DISCOUNTS",
  "CHANGE_SALE_PRICE",
  "VIEW_BILLS",
  "MANAGE_CUSTOMERS",
  "RECEIVE_PAYMENTS",
  "ADJUST_LEDGER",
  "VIEW_LEDGER",
  "VIEW_REPORTS",
  "MANAGE_USERS",
  "MANAGE_SETTINGS",
];

/** System roles created for every new business. Owner has everything. */
export const SYSTEM_ROLES: Record<string, Permission[]> = {
  Owner: ALL_PERMISSIONS,
  Admin: ALL_PERMISSIONS.filter((p) => p !== "MANAGE_SETTINGS"),
  Manager: [
    "VIEW_PRODUCTS",
    "ADD_PRODUCTS",
    "EDIT_PRODUCTS",
    "CHANGE_PRICES",
    "BULK_PRICE_UPDATE",
    "IMPORT_EXPORT",
    "CREATE_BILLS",
    "CANCEL_BILLS",
    "APPLY_DISCOUNTS",
    "CHANGE_SALE_PRICE",
    "VIEW_BILLS",
    "MANAGE_CUSTOMERS",
    "RECEIVE_PAYMENTS",
    "VIEW_LEDGER",
    "VIEW_REPORTS",
  ],
  Cashier: [
    "VIEW_PRODUCTS",
    "CREATE_BILLS",
    "APPLY_DISCOUNTS",
    "VIEW_BILLS",
    "MANAGE_CUSTOMERS",
    "RECEIVE_PAYMENTS",
  ],
};

export const PERMISSION_LABELS: Record<Permission, string> = {
  VIEW_PRODUCTS: "View products",
  ADD_PRODUCTS: "Add products",
  EDIT_PRODUCTS: "Edit products",
  DELETE_PRODUCTS: "Delete products",
  CHANGE_PRICES: "Change prices",
  BULK_PRICE_UPDATE: "Bulk price updates",
  IMPORT_EXPORT: "Excel import / export",
  CREATE_BILLS: "Create bills",
  CANCEL_BILLS: "Cancel bills",
  APPLY_DISCOUNTS: "Apply discounts",
  CHANGE_SALE_PRICE: "Change price during billing",
  VIEW_BILLS: "View bills",
  MANAGE_CUSTOMERS: "Manage customers",
  RECEIVE_PAYMENTS: "Receive udhaar payments",
  ADJUST_LEDGER: "Ledger adjustments",
  VIEW_LEDGER: "View ledger",
  VIEW_REPORTS: "View reports",
  MANAGE_USERS: "Manage users",
  MANAGE_SETTINGS: "Manage business settings",
};
